[package]
name = "misterfpga_font_randomizer"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-ini = "0.18"
rand = "0.8.4"

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
panic = "abort"
